spring.application.name=EVProject

# Oracle JNDI
spring.datasource.jndi-name=java:/OracleDS

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
# Removing default_schema so that the schema of the JDBC user is used (SYSTEM for the current JNDI datasource).
# If your tables live in another user/schema, either set this property accordingly or change
the datasource credentials to that schema.
spring.jpa.properties.hibernate.default_schema=dacons16

# Mail Config for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cebevproject@gmail.com
spring.mail.password=jvib gttp ubei iyhj
spring.mail.protocol=smtp

# Gmail SMTP properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Optional debug to see what's happening
spring.mail.properties.mail.debug=true

# Server Settings (HTTPS Disabled for easier React connectivity)
server.port=8088
server.ssl.enabled=false

# App Settings
app.base-url=http://localhost:8088/EV
app.otp.expiry-minutes=10
# Billing API endpoint
billing.api.url=http://10.128.1.126/SolarSmartPlug/api/smartplugsendtobilling

server.undertow.websocket.idle-timeout=3600000 

# OCPP Settings
ocpp.heartbeat.interval=300
ocpp.authorize.retry.interval=30
ocpp.authorize.max.retries=10

