# application name
spring.application.name=EVProject

# jndi name for oracle datasource configured in wildfly
spring.datasource.jndi-name=java:/NewEvDS

spring.session.store-type=none

# jpa / hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect.oracle.pagination_strategy=rownum
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=NEWEV
spring.main.allow-circular-references=true

# logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# session config
server.servlet.session.timeout=600s

# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cebevproject@gmail.com
spring.mail.password=jvib gttp ubei iyhj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=admin
spring.security.user.password=admin123

app.base-url=http://localhost:8080
app.otp.expiry-minutes=10

# Billing API endpoint
billing.api.url=http://10.128.1.126/SolarSmartPlug/api/smartplugsendtobilling

# ===== HTTPS configuration =====
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=ceb-ev-app

server.undertow.websocket.idle-timeout=3600000 

# OCPP Settings
ocpp.heartbeat.interval=300
ocpp.authorize.retry.interval=30
ocpp.authorize.max.retries=10

## redis (disabled)
# spring.session.store-type=redis
# spring.data.redis.host=localhost
# spring.data.redis.port=6379